cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:choice_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:choice_id>/',
         views.cart_remove,
         name='cart_remove'),
]

food_delivery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('kitchen.urls', namespace='kitchen')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

kitchen/urls.py
from django.urls import path
from . import views

app_name = 'kitchen'

urlpatterns = [
    path('', views.choice_list, name='choice_list'),
    path('<slug:menu_slug>/', views.choice_list,
         name='choice_list_by_menu'),
    path('<int:id>/<slug:slug>/', views.choice_detail,
         name='choice_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

kitchen/models.py
from django.db import models
from django.urls import reverse


class Menu(models.Model):
    name = models.CharField("Меню", max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'menu'
        verbose_name_plural = 'menus'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('kitchen:choice_list_by_menu',
                           args=[self.slug])


class Choice(models.Model):
    menu = models.ForeignKey(Menu,
                                 related_name='wide_choice',
                                 on_delete=models.CASCADE)
    name = models.CharField("Наименование блюд", max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='wide_choice/%Y/%m/%d',
                              blank=True)
    description = models.TextField("Описание", blank=True)
    price = models.DecimalField("Стоимость, руб.", max_digits=10, decimal_places=2)
    available = models.BooleanField("Внесение в прайс", default=True)
    created = models.DateTimeField("Дата внесения", auto_now_add=True)
    updated = models.DateTimeField("Дата изменения", auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('kitchen:choice_detail',
                           args=[self.id, self.slug])

orders/models.py
from django.db import models
from kitchen.models import Choice


class Order(models.Model):
    first_name = models.CharField("Имя", max_length=50)
    last_name = models.CharField("Фамилия", max_length=50)
    email = models.EmailField()
    address = models.CharField("Адрес", max_length=250)
    postal_code = models.CharField("Почтовый индекс", max_length=20)
    city = models.CharField("Город", max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField("Оплачиваемый", default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField("Стоимость", max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField("Количество", default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

cart/forms.py
from django import forms


CHOICE_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddChoiceForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=CHOICE_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

kitchen/views.py
from django.shortcuts import render, get_object_or_404
from .models import Menu, Choice
from cart.forms import CartAddChoiceForm

def choice_list(request, menu_slug=None):
    menu = None
    menus = Menu.objects.all()
    wide_choice = Choice.objects.filter(available=True)
    if menu_slug:
        menu = get_object_or_404(Menu, slug=menu_slug)
        wide_choice = wide_choice.filter(menu=menu)
    return render(request,
                  'kitchen/choice/list.html',
                  {'menu': menu, 'menus': menus,
                   'wide_choice': wide_choice})

def choice_detail(request, id, slug):
    choice = get_object_or_404(Choice, id=id, slug=slug, available=True)
    cart_choice_form = CartAddChoiceForm()
    return render(request,
                  'kitchen/choice/detail.html',
                  {'choice': choice,
                   'cart_choice_form': cart_choice_form})

orders/views.py
from django.shortcuts import render

# Create your views here.

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Ваша корзина
{% endblock %}

{% block content %}
  <h1>Ваша корзина</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукты</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Цена за единицу</th>
        <th>Стоимость</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with choice=item.choice %}
          <tr>
            <td>
              <a href="{{ choice.get_absolute_url }}">
                <img src="{% if choice.image %}{{ choice.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ choice.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" choice.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url "cart:cart_remove" choice.id %}">Удалить</a></td>
            <td class="num">{{ item.price }} руб.</td>
            <td class="num">{{ item.total_price }} руб.</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Итого</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }} руб.</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "kitchen:choice_list" %}" class="button light">Продолжите заказы</a>
    <a href="# "  class="button">
      Проверка
    </a>
  </p>
{% endblock %}

kitchen/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}Доставка обедов{% endblock %}</title>
  <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
  <div id="header">
    <a href="/" class="logo">Доставка обедов</a>
  </div>
  <div id="subheader">
    <div class="cart">
      {% with total_items=cart|length %}
          {% if cart|length > 0 %}
            Ваша корзина:
            <a href="{% url "cart:cart_detail" %}">
              {{ total_items }} ед.  на сумму {{ total_item|pluralize }},
              {{ cart.get_total_price }} руб.
            </a>
          {% else %}
            Корзина без заказов
          {% endif %}
        {% endwith %}
    </div>
  </div>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

kitchen/templates/kitchen/choice/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ choice.name }}
{% endblock %}

{% block content %}
  <div class="choice-detail">
    <img src="{% if choice.image %}{{ choice.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
    <h1>{{ choice.name }}</h1>
    <h2><a href="{{ choice.menu.get_absolute_url }}">{{ choice.menu }}</a></h2>
    <p class="price">{{ choice.price }} руб.</p>
    <form action="{% url "cart:cart_add" choice.id %}" method="post">
      {{ cart_choice_form }}
      {% csrf_token %}
      <input type="submit" value="Добавить в корзину">
    </form>
    {{ choice.description|linebreaks }}
  </div>
{% endblock %}

kitchen/templates/kitchen/choice/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {% if menu %}{{ menu.name }}{% else %}Выбор продуктов{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Варианты меню</h3>
    <ul>
      <li {% if not menu %}class="selected"{% endif %}>
        <a href="{% url 'kitchen:choice_list' %}">Все</a>
      </li>
      {% for c in menus %}
        <li {% if menu.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="choice_list">
    <h1>{% if menu %}{{ menu.name }}{% else %}Выбор продуктов{% endif %}</h1>
    {% for choice in wide_choice %}
      <div class="item">
        <a href="{{ choice.get_absolute_url }}">
          <img src="{% if choice.image %}{{ choice.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ choice.get_absolute_url }}">{{ choice.name }}</a><br>
        {{ choice.price }} руб.
      </div>
    {% endfor %}
  </div>
{% endblock %}